version: '3.6'
services:
  jupyter:
     build:
       context: .
       dockerfile: ./binder/Dockerfile
       target: jupyter
     volumes:
       - ./work:/home/jovyan/work
     ports:
        - 8888:8888
